### ISSUE TITLE
If internet is present then it should just directly launch the gateway

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway-wifi-setup#20] opened 2017-12-06 21:00 UTC
You shouldn't have to connect to the gateway AP and press skip.

**Comment by dhylands** [comment] 2017-12-07 17:40
This perhaps might be worded slightly differently. Rather than 'hard-wired ethernet' it should probably read 'internet'. We could perhaps perform some type of ping to see if the mozilla-iot.org server is available.

**Comment by benfrancis** [comment] 2017-12-07 18:40
I agree you shouldn't have to connect to the gateway WiFi AP in order to enable Ethernet. Hypothetically you may not have a WiFi capable client and therefore can't configure the gateway.

For the 0.3 release:
1. You should be able to initiate first time setup either using Ethernet or via the built-in WiFi access point.
2. You should be offered the option of connecting to a WiFi network during first time setup, regardless of whether you're accessing the first time setup via Ethernet, or the built-in WiFi AP.
3. Clicking skip on the WiFi setup in first time setup should disable the WiFi access point so that someone else can't reconfigure your gateway.

After the 0.3 release:
4. You should be able to change network settings after first time setup, including connecting to a WiFi network if you previously skipped that option. That's covered by issue #423 in the backlog.

**Comment by dhylands** [comment] 2017-12-07 18:51
3 & 4 seem to be in conflict with each other.

I also think that its worth separating the discussion of first time setup from non first time setup. i.e. I've moved and need to connect to a new wifi network. 

I'm not sure how https://github.com/mozilla-iot/gateway/issues/423 helps with the second part of 4 since that seems to assume that you have network connectivity (i.e. how do you get into Network Settings when the device can't connect to a network). It's great if you remember to reconfigure first, but having just moved, I know I didn't reconfigure any of my devices before moving.

**Comment by benfrancis** [comment] 2017-12-08 12:22
> 3 & 4 seem to be in conflict with each other.

Only in the edge case where both:
1. The previously used network is no longer available
2. For some reason you can't connect to the new network by just plugging the gateway into an Ethernet port and getting a new IP address via DHCP

> I'm not sure how mozilla-iot/gateway#423 helps with the second part of 4 since that seems to assume that you have network connectivity (i.e. how do you get into Network Settings when the device can't connect to a network). It's great if you remember to reconfigure first, but having just moved, I know I didn't reconfigure any of my devices before moving.

Again, I would suggest that in many/most cases you could just plug the gateway into an Ethernet port and get a new IP address via DHCP (unless the gateway is actually the router and DHCP server in which case you don't need to do that!).

If no Ethernet connection is available and you want to switch to a different WiFi network then you'll need to be able to do some kind of reset on the network settings. This problem is obviously not unique to our gateway but is common to any headless networked device. I imagine for things like an IP camera the simplest solution is just to do a factory reset. You might not want to do a full reset in the case of the gateway because you might want to preserve some settings. On a consumer gateway with buttons on it it's possible this could be achieve with a certain combination of key presses. On a developer board you probably have the option of logging in over the serial port and configuring it on the command line, though obviously not as user friendly.

Given that we don't want the open Access Point to randomly start up again for security reasons, what solution do you suggest?

Note that whilst moving house is an important use case which is often overlooked in smart home systems, it is kind of an edge case at this point. I don't imagine many people are going to be moving house with version 0.3 of our gateway being a key part of their smart home system! We should optimise for first time setup first, then settings second. As long as we have terminal access to the gateway, there will always be a way to change these settings manually.

**Comment by benfrancis** [comment] 2017-12-08 12:35
I suppose one use case *we* currently have is reconfiguring a gateway for WiFi at conferences! It's fairly easy for us to work around this by dropping a file onto the SD card, as long as we have a laptop and an SD card reader and there's no captive portal involved. But it would useful to be able to do it through the UI if there's an obvious solution which doesn't compromise security when used in its intended setting (the home).

**Comment by dhylands** [comment] 2017-12-08 19:32
Some solutions spring to mind that could be used to "reset Wifi settings" or enable "go into AP mode if no internet is detected"
1 - detect a jumper across a couple of GPIO pins
2 - detect a file on the sdcard
3 - have a network setting (disabled by default). This would require enabling the setting before going to  a show or conference.

**Comment by benfrancis** [comment] 2018-01-15 15:42
> If internet is present then it should just directly launch the gateway

I'm not sure this is actually what we want? If you plug the gateway into Ethernet for first time setup you should still be given the option of connecting to a WiFi network.

**Comment by dhylands** [comment] 2018-01-15 17:32
I think its also worth splitting this discussion into 2 parts. How we want things to behave during first time setup and how we want things to behave after the device is already setup.

I don't have an issue with configuring Wifi during first time setup. Once the device is setup, I should be able to plug in ethernet and not have to change any other configuration on the device to make it work.

**Comment by andrenatal** [comment] 2018-01-15 19:04
I'm  confused too. [This](https://github.com/mozilla-iot/gateway-wifi-setup/issues/20#issue-279904546) and [this comment](https://github.com/mozilla-iot/gateway-wifi-setup/issues/20#issuecomment-350041214) says 

> You shouldn't have to connect to the gateway AP and press skip.

> This perhaps might be worded slightly differently. Rather than 'hard-wired ethernet' it should probably read 'internet'. We could perhaps perform some type of ping to see if the mozilla-iot.org server is available.


While [this](https://github.com/mozilla-iot/gateway-wifi-setup/issues/20#issuecomment-350056884) says

> You should be offered the option of connecting to a WiFi network during first time setup, regardless of whether you're accessing the first time setup via Ethernet, or the built-in WiFi AP.

So it is a little confusing too me what I should do. 

What is mentioned [here] (https://github.com/mozilla-iot/gateway-wifi-setup/issues/20#issuecomment-357717876) is already how the application behaves. So if this what we want, I'll close this,

**Closed as completed by andrenatal** 2018-01-15 19:04 UTC

**Comment by benfrancis** [comment] 2018-01-15 19:25
Sorry if the back and forth has caused confusion. See the UI specification for the expected behaviour https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g221d7d7c9f_0_0

> On first boot the gateway acts as a WiFi hotspot which the user can connect to from any device. The WiFi hotspot redirects all HTTP requests to the first time setup page at gateway.local using captive portal. Alternatively the user can manually navigate to gateway.local (broadcast via mDNS) in their browser via the WiFi hotspot or by plugging the gateway into an Ethernet port on a router which provides it an IP address via DHCP.

In other words, regardless of how you initially connect to the gateway for first time setup (WiFi or Ethernet), you should be given the option to connect to a WiFi network during the setup process, or choose to skip connecting to a WiFi network which should then disable the WiFi hotspot and captive portal. Is that clearer?

**Comment by benfrancis** [comment] 2018-01-15 19:31
> You shouldn't have to connect to the gateway AP and press skip.

To be completely clear, you shouldn't have to connect to the WiFi access point if you instead want to use Ethernet, but you should still be offered the option to connect to a WiFi network if you're connected by Ethernet and would then need to click "skip" to continue using Ethernet and not WiFi.

If that's how the implementation currently behaves, then yes this issue can be closed.

(The issue title was wrong, it contradicts the specification).
