### ISSUE TITLE
Make "gateway.local" message a link

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway-wifi-setup#50] opened 2018-01-31 18:32 UTC
During first time setup there's a message which tells you to type gateway.local into your browser. It would be nice if this was a link so I don't have to type it in!

Would need testing in the captive portal UI to check it opens in a separate browser window (target=blank?).

**Comment by andrenatal** [comment] 2018-02-09 22:14
I just tested this on OSX and got an error when clicked the link:

<img width="909" alt="screenshot 2018-02-09 14 12 54" src="https://user-images.githubusercontent.com/973388/36052681-8160df62-0da3-11e8-8474-906cbda450b4.png">

**Comment by dhylands** [comment] 2018-02-09 23:12
It can take quite a while before gateway.local is actually available.

**Comment by mrstegeman** [comment] 2018-02-09 23:13
Yeah... Up to a minute or 2 in my experience.

**Comment by andrenatal** [comment] 2018-02-09 23:21
For me the link never worked, because as I said the captive portal automatically closes after hostapd shutdowns and my computer disconnects from the hotspot. When tested on Android, the new browser didn't open. Where did you test this @mrstegeman so I can reproduce here?

**Comment by mrstegeman** [comment] 2018-02-09 23:26
I tested on my RPi and pulled up the captive portal in Firefox on my laptop.

**Comment by andrenatal** [comment] 2018-02-09 23:44
Ah ok, yes, when accessing through the browser process that makes sense, but when accessing the native captive portal browser from the OS I am not sure if it will work. The captive portal on Windows opens a browser, so this approach will work. But OSX, iOS and Android opens a native browser window.

**Comment by andrenatal** [comment] 2018-02-09 23:46
I'll close this since what the issue stated was addressed.

**Closed as completed by andrenatal** 2018-02-09 23:46 UTC
Labels: task
